# Generated by Django 3.0.6 on 2021-05-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
