# Generated by Django 3.0.6 on 2021-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210509_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_key',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
